/* ==========================================================================
   Vorbraut 14 — textainnihald (íslenska / English)
   Íslenski textinn byggir á vinnuskjali verkefnisins.
   ========================================================================== */
const STR = {
  is: {
    /* CMS — vörumerki, hetja, söluaðilar, footer (allt ritstýranlegt) */
    'brand.logo': 'VORBRAUT 14',
    'hero.name': 'Vorbraut',
    'hero.no': '14',
    'sellers.brand1': 'Fasteignasalan',
    'sellers.brand2': 'MIKLABORG',
    'foot.addr1': 'Vorbraut 14, Hnoðraholt',
    'foot.addr2': '210 Garðabær',
    'foot.landnr': 'L232219',
    'foot.email': 'miklaborg@miklaborg.is',
    'foot.phone': 'S: 569 7000',
    'ag.1.name': 'Steinn Andri Viðarsson',
    'ag.1.title': 'Löggiltur fasteigna- og skipasali',
    'ag.1.phone': '775‑1477',
    'ag.1.email': 'steinn@miklaborg.is',
    'ag.2.name': 'Guðrún Gonnigan Daníelsdóttir',
    'ag.2.title': 'Löggiltur fasteignasali',
    'ag.2.phone': '897‑1161',
    'ag.2.email': 'gudrun@miklaborg.is',
    'ag.3.name': 'Kjartan Ísak Guðmundsson',
    'ag.3.title': 'Löggiltur fasteignasali',
    'ag.3.phone': '663‑4392',
    'ag.3.email': 'kjartan@miklaborg.is',
    'ag.4.name': 'Kristín Pétursdóttir',
    'ag.4.title': 'Löggiltur fasteigna- og skipasali',
    'ag.4.phone': '824‑1965',
    'ag.4.email': 'kristin@miklaborg.is',
    /* ---- nav + pager (undirsíður) ---- */
    'nav.verkefnid': 'Verkefnið',
    'nav.arkitektur': 'Arkitektúr',
    'nav.husid': 'Húsið',
    'nav.utsyni': 'Útsýni og útirými',
    'nav.utirymi': 'Útirými',
    'nav.adgengi': 'Aðgengi',
    'nav.hverfid': 'Hverfið',
    'nav.menu': 'Valmynd',
    'pager.prev': 'Fyrra',
    'pager.next': 'Næsta',
    'pager.home': 'Forsíða',
    'pager.ibudir': 'Skoða íbúðir',
    /* ---- story sections ---- */
    'fig.label': 'Mynd',
    'kj.kick': 'Neðanjarðar',
    'kj.title': 'Bílakjallarinn',
    'kj.sub': 'Tíu bílastæði og sérgeymsla fyrir hverja íbúð. Lyftan gengur niður í kjallarann af öllum hæðum.',
    'kort.kick': 'Í göngufæri',
    'kort.title': 'Þjónustukort',
    'kort.sub': 'Allt á kortinu er innan 1,5 km frá Vorbraut 14, mælt í loftlínu.',
    'kort.credit': 'Kortagögn © OpenStreetMap-höfundar',
    'kort.swipe': 'Strjúktu til hliðar til að skoða kortið.',
    'fig.viz': 'Tölvumynd',
    'swipe.adur': 'Áður',
    'swipe.eftir': 'Eftir',
    'st.intro.kick': '01 · Vorbraut 14',
    'st.intro.title': 'Heillandi búseta í Garðabæ',
    'st.intro.pull': 'Birta, víðsýni og náttúra í Garðabæ',
    'st.intro.lvl': 'Lóðin og heildarmyndin',
    'st.intro.cap': 'Línuteikning af Vorbraut 14 — form og hlutföll.',
    'st.intro.cap2': 'Sama sjónarhorn: húsið á byggingartíma og fullbyggt.',
    'st.intro.cap3': 'Framhliðin á byggingartíma, með byggðina í baksýn.',
    'st.intro.b1': 'Við Vorbraut 14 í Hnoðraholti í Garðabæ rís vandað fjögurra hæða fjölbýlishús sem hýsir 14 fjölbreyttar íbúðir ásamt bílakjallara og ríkulegum stoðrýmum. Verkefnið leggur ríka áherslu á dagsbirtu, útsýni, fyrirmyndar aðgengi og heilsteypta hönnun, enda nýtur byggingin einstakrar staðsetningar ofarlega í landslaginu. Húsið stendur á friðsælum og eftirsóknarverðum stað þar sem nálægð við ósnortna náttúru, fjölbreytta þjónustu og helstu samgönguæðar rennur saman í eina heild. Hér gefst tækifæri á framtíðarheimili þar sem ríkidæmi hversdagsins endurspeglast í hugvitsamlegu skipulagi, vönduðum útirýmum og nútímaþægindum. Vorbraut 14 er kjörinn kostur fyrir þá sem gera miklar kröfur til búsetu í Garðabæ, þar sem víðsýni og birta eru í fyrirrúmi, en þjónusta og útivist aldrei langt undan.',
    'st.intro.c1': '14 íbúðir',
    'st.intro.c2': 'Fjórar hæðir',
    'st.intro.c3': 'Hnoðraholt, Garðabær',
    'st.intro.c4': 'Dagsbirta og útsýni',
    'st.arch.kick': '02 · Hönnun',
    'st.arch.title': 'Arkitektúr',
    'st.arch.pull': 'Fágað form í samhljómi við Hnoðraholt',
    'st.arch.lvl': 'Allar hæðir hússins',
    'st.arch.cap': 'Framhliðin: hvítir fletir og viðarklæddir stallar.',
    'st.arch.cap2': 'Skissa af húsinu — frá hugmynd að veruleika.',
    'st.arch.b1': 'Arkitektúr Vorbrautar 14 er yfirvegaður og stílhreinn, þar sem skýr áhersla er lögð á fágað yfirbragð og samhljóm við nærumhverfið. Byggingin, sem er verk Guðmundar Gunnlaugssonar arkitekts hjá Archus, er nátengd landslagi Hnoðraholts, dregur dám af útsýninu og fellur vel að þeirri uppbyggingu sem á sér stað á svæðinu. Húsið skartar fáguðu, kröftugu og nútímalegu útliti þar sem formrænn hreinleiki, efnisval og áferð mynda sannfærandi heild. Ytra byrði byggingarinnar er varið vandaðri álklæðningu þar sem flötum er brotið upp með mismunandi áferð til að gefa ásýndinni aukna dýpt. Inndregin efsta hæð gefur húsinu léttara yfirbragð á sama tíma og hún skapar svigrúm fyrir einkar glæsilegar þaksvalir. Á þennan hátt er víðáttumikið útsýnið nýtt til fulls og gert að óaðskiljanlegum hluta af híbýlum íbúanna. Hönnunin byggir á því að draga fram kosti staðhátta, en niðurstaðan er mannvirki sem einkennist af efnislegum gæðum, fágun og yfirvegandi virðuleika.',
    'st.arch.c1': 'Álklæðning',
    'st.arch.c2': 'Inndregin efsta hæð',
    'st.arch.c3': 'Archus',
    'st.arch.c4': 'Guðmundur Gunnlaugsson',
    'arch.name': 'Guðmundur Gunnlaugsson',
    'arch.role': 'Arkitekt hússins',
    'st.house.kick': '03 · Heimilin',
    'st.house.title': 'Húsið',
    'st.house.pull': 'Fjórtán íbúðir, ótal leiðir til að búa',
    'st.house.lvl': '1.–4. hæð',
    'st.house.cap': 'Bakhliðin: fjórtán íbúðir á fjórum hæðum.',
    'st.house.cap2': 'Framhliðin og aðkoman að aðalinngangi.',
    'st.house.b1': 'Húsið að Vorbraut 14 er vandað, fjögurra hæða fjölbýlishús með lyftu sem hýsir 14 vel skipulagðar íbúðir. Lögð er áhersla á að mæta ólíkum þörfum fólks, hvort sem um er að ræða fyrstu kaup, stækkun eða minnkun við sig. Úrvalið spannar allt frá hagkvæmum stúdíóíbúðum upp í rúmgóðar fjölskylduíbúðir þar sem björt alrými fá að njóta sín til fulls.',
    'st.house.b2': 'Við hönnun íbúðanna var unnið markvisst með opið flæði og skýra tengingu milli innan- og utandyra. Stórir gluggar fanga dagsbirtuna á fallegan hátt, auka rýmistilfinningu og draga umhverfið beint inn í stofu.',
    'st.house.b3': 'Útirýmin eru kærkomin framlenging á heimilinu. Frá íbúðum á jarðhæð er gengið beint út á stóra sérverönd sem færir garðinn og gróðurinn nær. Á efri hæðum taka við svalir og glæsilegar þaksvalir sem bjóða upp á notalega útiveru og fallegt útsýni yfir byggðina.',
    'st.house.b4': 'Dagleg þægindi skila sér einnig í öllum stoðrýmum. Undir húsinu er lokaður bílakjallari þar sem einkageymsla fylgir hverri íbúð, og þaðan tryggir lyfta greiða leið upp á allar hæðir. Til viðbótar er í húsinu rúmgóð hjóla- og vagnageymsla sem einfaldar heimilislífið verulega og styður vel við virkan lífsstíl.',
    'st.house.c1': 'Lyftuhús',
    'st.house.c2': 'Stúdíó til fjölskylduíbúða',
    'st.house.c3': 'Sérafnotareitir á jarðhæð',
    'st.house.c4': 'Stórir gluggar',
    'st.view.kick': '04 · Sjónarhorn',
    'st.view.title': 'Útsýni',
    'st.view.pull': 'Útsýnið opnast eftir því sem ofar dregur',
    'st.view.lvl': 'Efstu hæðir og þak',
    'st.view.cap': 'Hnoðraholt úr lofti — hverfið og golfvöllurinn.',
    'st.view.cap2': 'Vífilsstaðavatn, golfvöllurinn og fjallahringurinn.',
    'st.view.b1': 'Hæðótt og opin staðsetning Vorbrautar 14 er ótvíræður kostur verksins. Húsið býður upp á víðáttumikla og fagra sjón yfir bæinn og aðliggjandi náttúru, og sýnin opnast enn frekar eftir því sem ofar dregur. Arkitektúr hússins tekur djúpt mið af þessum sérstöku gæðum. Stórir gluggar og svalir ramma inn umhverfið þannig að samband við náttúruna, birtuna og útsýnið fléttast inn í tilveru dagsins í dag. Víðsýnið færir híbýlunum ómetanlegan fjársjóð og undirstrikar þá tilfinningu að rými heimilanna takmarkist ekki einungis af veggjum þeirra.',
    'st.view.c1': 'Víðáttumikið útsýni',
    'st.view.c2': 'Útsýni yfir bæinn',
    'st.view.c3': 'Svalir',
    'st.view.c4': 'Hæðótt landslag',
    'st.outdoor.kick': '05 · Náttúran',
    'st.outdoor.title': 'Útirými',
    'st.outdoor.pull': 'Útirýmin stækka heimilið og færa náttúruna nær',
    'st.outdoor.lvl': 'Sérafnotareitir og þaksvalir',
    'st.outdoor.cap': 'Lóðin, grasflatirnar og gróðurþekjan úr lofti.',
    'st.outdoor.cap2': 'Aðkoma, gróður og sérafnotareitir á jarðhæð.',
    'st.outdoor.b1': 'Útirými eignarinnar gegna lykilhlutverki í búsetugæðum Vorbrautar 14. Þeir sem búa á jarðhæð eiga þess kost að njóta dvalar á sérafnotareitum sem skapa nálægð og góð tengsl við gróskumikið umhverfið. Sömuleiðis skapa svalir og þaksvalir efri hæða tækifæri til að njóta bæði fersks lofts og óviðjafnanlegs útsýnis. Á hluta þaksins er komið fyrir gróðurþekju sem mildar yfirbragð mannvirkisins og tónar fallega við náttúruleg einkenni holtsins. Lóðin nýtir jafnframt blágrænar lausnir til ofanvatnsmeðhöndlunar sem fellur afar vel að snyrtilegri ásýnd svæðisins. Þannig stækka útirýmin heimilið og styrkja lífsgæðin með því að færa umhverfið nær íbúum.',
    'st.outdoor.c1': 'Sérafnotareitir',
    'st.outdoor.c2': 'Gróðurþekja',
    'st.outdoor.c3': 'Blágrænar lausnir',
    'st.outdoor.c4': 'Ofanvatnsmeðhöndlun',
    'st.access.kick': '06 · Þægindi',
    'st.access.title': 'Aðgengi og stoðrými',
    'st.access.mark': 'Kjallari',
    'st.access.pull': 'Hugsað fyrir hverjum degi, frá kjallara upp á þak',
    'st.access.lvl': 'Bílakjallari og stoðrými',
    'st.access.cap': 'Aðalinngangurinn með aðgengisramp að dyrum.',
    'st.access.cap2': 'Innkeyrslan niður í lokaðan bílakjallara.',
    'st.access.b1': 'Óaðfinnanleg dagsdagleg þægindi eru rauður þráður í verkinu. Rúmgóð lyfta gengur milli allra hæða og bílakjallara, sem tryggir algilt og greitt aðgengi. Í lokuðum bílakjallaranum er gert ráð fyrir sérstæðum og einkageymslu fyrir hverja íbúð. Íbúum stendur jafnframt til boða rúmgóð hjóla- og vagnageymsla sem styður sérlega vel við fólk á ferðinni og barnafjölskyldur. Öll þessi rými miða að því að skapa umgjörð fyrir skipulagt og einfalt heimilislíf þar sem dagleg notkun hússins er áreynslulaus. Sorpmálum er komið haganlega fyrir með niðurgröfnum djúpgámum sem auka bæði hreinlæti og fagurfræði nærumhverfisins.',
    'st.access.c1': 'Rúmgóð lyfta',
    'st.access.c2': 'Lokaður bílakjallari',
    'st.access.c3': 'Einkageymsla',
    'st.access.c4': 'Hjóla- og vagnageymsla',
    'st.access.c5': 'Niðurgrafnir djúpgámar',
    'st.hood.kick': '07 · Staðsetning',
    'st.hood.title': 'Hverfið',
    'st.hood.mark': 'Holtið',
    'st.hood.pull': 'Þar sem náttúran og bærinn mætast',
    'st.hood.lvl': 'Hnoðraholt í Garðabæ',
    'st.hood.cap': 'Vífilsstaðavatn og golfvellirnir í Vetrarmýri.',
    'st.hood.cap2': 'Útivist, þjónusta og stofnbrautir í göngufæri.',
    'st.hood.b1': 'Hnoðraholt er spennandi og blómlegt íbúðahverfi sem býður upp á samruna ósnortinnar náttúru og stuttra leiða að samgöngum og þjónustu. Hverfið situr nærri helstu slagæðum svæðisins en varðveitir samt rólega og fjölskylduvæna eiginleika þar sem útivistarskilyrði eru ákjósanleg. Greið og þægileg leið er í vinsæl útivistarsvæði á borð við Vífilsstaðavatn, göngu- og hjólaleiðir Heiðmerkur sem og golfvöllinn hjá GKG. Búseta hér hentar því einkar vel þeim sem kjósa að sækja beint í útivist og ferskt loft með lítilli fyrirhöfn. Samhliða náttúrunni skartar Garðabær ríkulegu framboði af afþreyingu og þjónustu. Vandaðar verslanir, frambærilegir veitingastaðir, íþróttamiðstöðvar og sterkir innviðir skapa í senn lífleg og örugg búsetu fyrir borgara á öllum aldri.',
    'st.hood.c1': 'Vífilsstaðavatn',
    'st.hood.c2': 'Heiðmörk',
    'st.hood.c3': 'GKG golfvöllur',
    'st.hood.c4': 'Fjölskylduvænt',
    /* chrome */
    'nav.house': 'Húsið',
    'nav.ibudir': 'Íbúðir',
    'nav.stadsetning': 'Staðsetning',
    'nav.honnun': 'Hönnun',
    'nav.gaedi': 'Gæði',
    'nav.hverfi': 'Hverfi',
    'nav.contact': 'Hafa samband',
    'cta.ibudir': 'Skoða íbúðir',
    'cta.contact': 'Hafa samband',
    'cta.enquiry': 'Senda fyrirspurn',
    'cta.plan': 'Skoða grunnmynd',
    'scroll': 'Skruna',

    /* hero */
    'hero.kicker': 'Hnoðraholt · Garðabær',
    'hero.eyebrow': 'Vorbraut 14 · Hnoðraholt',
    'hero.headline': 'Vandaðar íbúðir á einstökum stað',
    'hero.h1': 'Vandaðar',
    'hero.h2': 'íbúðir',
    'hero.h3': 'á einstökum stað',
    'hero.lead': 'Veldu íbúð og skoðaðu staðsetningu, stærð, skipulag og sölustöðu.',
    'hero.title': 'Vorbraut 14',
    'hero.tag': 'Vandaðar íbúðir í Hnoðraholti í Garðabæ.',
    'hero.sub': 'Nýjar íbúðir í Garðabæ eru komnar á sölu.',
    'stat.ibudir': 'íbúðir',
    'stat.haedir': 'hæðir',
    'stat.bilastaedi': 'bílastæði',
    'stat.fra': 'm² frá',

    /* staðsetning / bílastæði */
    'loc.kicker': '02 — Staðsetning',
    'loc.title': 'Næg bílastæði og frábær staðsetning',
    'loc.body': 'Vorbraut 14 stendur í Hnoðraholti í Garðabæ, í rólegu og fjölskylduvænu umhverfi með útivist í næsta nágrenni og góðri tengingu við stofnbrautir.',
    'loc.p1.t': '10 bílastæði',
    'loc.p1.b': 'Öll 10 stæðin eru í lokaðri, læstri bílgeymslu.',
    'loc.p2.t': 'Rafhleðsla undirbúin',
    'loc.p2.b': 'Gert ráð fyrir að rafhleðslubúnaður verði auðveldur í uppsetningu, bæði í bílgeymslu og við stæði á lóð.',
    'loc.p3.t': 'Geymslur og hjólastæði',
    'loc.p3.b': 'Í kjallara eru sérgeymslur fyrir hverja íbúð og rúmgóð hjóla- og vagnageymsla.',
    'loc.p4.t': 'Aðgengi fyrir alla',
    'loc.p4.b': 'Lyfta fyrir miðju húsi og algild hönnun tengja íbúðir, sameignir og bílakjallara.',

    /* íbúðir intro */
    'apt.kicker': '03 — Íbúðir',
    'apt.title': 'Bjartar íbúðir, hannaðar til að lifa í',
    'apt.body': 'Íbúðirnar eru frá tveggja herbergja íbúðum upp í rúmgóðar fjögurra herbergja íbúðir á efstu hæð. Áhersla er lögð á gott innra flæði, dagsbirtu og notagildi. Gólfhiti er í öllum íbúðum og vandað er til hljóðvistar.',
    'type.two.name': '2ja herbergja',
    'type.two.size': '69–70 m²',
    'type.two.desc': 'Hagkvæmar og vel nýttar íbúðir fyrir einstaklinga og pör.',
    'type.fam.name': '3ja–4ra herbergja',
    'type.fam.size': '102–118 m²',
    'type.fam.desc': 'Rúmgóðar fjölskylduíbúðir, m.a. með sérafnotareitum á jarðhæð.',
    'type.pent.name': 'Efsta hæð',
    'type.pent.size': '156–158 m²',
    'type.pent.desc': 'Stærri íbúðir með aukinni lofthæð og rúmgóðum þaksvölum.',

    /* gagnvirkt val */
    'sel.kicker': 'Íbúðir í Vorbraut 14',
    'sel.title': 'Veldu íbúð í húsinu',
    'sel.brand': 'Vorbraut 14',
    'av.tabPlan': 'Grunnmynd',
    'av.tabGarage': 'Sjá bílakjallara',
    'av.kjStaedi': 'Bílastæði',
    'av.kjGeymsla': 'Sérgeymsla',
    'av.kjEkkert': 'Þessari íbúð fylgir ekki bílastæði.',
    'av.cta': 'Senda fyrirspurn um þessa íbúð',
    'av.call': 'Eða hringdu í',
    'av.zoom': 'Smelltu á grunnmynd til að skoða í hærri upplausn',
    'av.spec': 'Skilalýsing',
    'av.garage': 'Grunnteikning bílakjallara',
    'kj.flatarmal': 'Bílageymsla',
    'kj.geymslur': 'Geymslur',
    'kj.adgengi': 'Aðgengi',
    'kj.adgengiGildi': 'Lyfta og rampur',
    'kj.cta': 'Sjá aðgengi',
    'facade.aftan': 'Bakhlið',
    'facade.framan': 'Framhlið',
    'facade.hlid': 'Hliðin',
    'facade.kjallari': 'Bílakjallari',
    'sel.pickFloor': 'Veldu hæð',
    'sel.pickApt': 'Veldu íbúð',
    'sel.body': 'Færðu músina yfir framhlið hússins. Hver íbúð lýsist upp — smelltu til að sjá stærð, hæð, herbergi og grunnmynd.',
    'sel.bodyTouch': 'Smelltu eða ýttu á íbúð til að sjá teikningar, stærðir og nánari upplýsingar.',
    'sel.empty': 'Veldu íbúð á byggingunni eða á grunnmyndinni.',
    'sel.open': 'Skoða íbúð',
    'facade.front': 'Framhlið',
    'facade.back': 'Bakhlið',
    'sel.hint': 'Veldu íbúð á myndinni',
    'sel.legend.available': 'Til sölu',
    'sel.legend.reserved': 'Frátekin',
    'sel.legend.sold': 'Seld',

    /* yfirlit / filters */
    'list.kicker': '04 — Íbúðayfirlit',
    'list.title': 'Allar íbúðir',
    'filter.floor': 'Hæð',
    'filter.rooms': 'Herbergi',
    'filter.type': 'Gerð',
    'filter.all': 'Allar',
    'filter.reset': 'Hreinsa',
    'apts.title': 'Verðskrá',
    'apts.sub': 'Verð getur tekið breytingum',
    'apts.view': 'Skoða',
    'feat.title': 'Eiginleikar íbúða',
    'feat.parking': 'Sér bílastæði',
    'feat.pottur': 'Möguleiki á heitum potti',
    'feat.forsale': 'Einungis íbúðir í sölu',
    'sellers.title': 'Söluaðilar',
    'sellers.lead': 'Fasteignasalan Miklaborg hefur umsjón með sölu íbúða í Vorbraut 14. Hafðu samband við söluaðila fyrir nánari upplýsingar eða til að bóka einkaskoðun.',
    'list.count': 'íbúðir',
    'list.empty': 'Engin íbúð passar við valið. Hreinsaðu síur.',
    'col.id': 'Íbúð',
    'col.floor': 'Hæð',
    'col.size': 'Stærð',
    'col.rooms': 'Herbergi',
    'col.outdoor': 'Útisvæði',
    'col.status': 'Staða',

    /* labels */
    'lbl.floor': 'hæð',
    'lbl.rooms': 'herb.',
    'unit.rooms2': '2ja herb.',
    'unit.rooms3': '3ja herb.',
    'unit.rooms4': '4ra herb.',
    'out.verond': 'Verönd / sérafnotareitur',
    'out.svalir': 'Svalir',
    'out.thaksvalir': 'Þaksvalir',
    'st.available': 'Til sölu',
    'st.reserved': 'Selt með fyrirvara',
    'st.sold': 'Seld',
    'spec.ceiling': 'Salarhæð',
    'spec.area': 'Birt stærð',
    'modal.note': 'Stærðir og herbergjafjöldi samkvæmt aðaluppdráttum. Staðfestist í kaupsamningi.',
    'modal.planSoon': 'Dæmigerð grunnmynd fyrir þessa íbúðargerð.',
    'modal.planHint': 'Smelltu á grunnmyndina til að skoða í hærri upplausn.',
    'modal.planDisc': 'Um birta stærð íbúða/rýma er að ræða samkvæmt aðaluppdráttum. Vísað er í skráningartöflu varðandi brúttó- og birtar fermetrastærðir. Staðfestist í kaupsamningi.',
    'modal.floorLbl': 'Hæð',
    'spec.parking': 'Bílastæði',
    'spec.storage': 'Sérgeymsla',
    'spec.balcony': 'Svalir / verönd',
    'spec.laundry': 'Sér þvottahús',
    'spec.theme': 'Hönnunarþema',
    'spec.price': 'Verð',
    'spec.no': 'Nei',
    'spec.yes': 'Já',
    'spec.basement': 'Í kjallara',

    /* hönnun */
    'des.kicker': '05 — Hönnun',
    'des.title': 'Hreint og tímalaust',
    'des.body': 'Húsið er hannað af Guðmundi Gunnlaugssyni arkitekt hjá ARCHUS arkitektum. Hvítar álklæðningar, náttúruleg timburklæðning og glerhandrið létta ásýnd hússins. Kolsgráir gluggar og hlýir timburtónar skapa rólegt, norðlægt útlit sem fellur vel að umhverfi Hnoðraholts.',
    'des.architect': 'ARCHUS arkitektar — Guðmundur Gunnlaugsson',

    /* gæði */
    'q.kicker': '06 — Gæði',
    'q.title': 'Gæði samkvæmt aðaluppdráttum',
    'q.body': 'Vönduð efni, gott aðgengi og skýrt innra skipulag eru höfð að leiðarljósi í gegnum allt húsið.',
    'q.1': 'Gólfhiti í öllum íbúðum',
    'q.2': 'Vönduð hljóðvist og einangrun',
    'q.3': 'Náttúruleg loftræsing og vélrænt útsog',
    'q.4': 'Lyfta og algild hönnun',
    'q.5': 'Sorpflokkun í djúpgámum',
    'q.6': 'Möguleiki á rafhleðslu',
    'q.7': 'Stórir gluggar og góð dagsbirta',
    'q.8': 'Þaksvalir með aukinni lofthæð á efstu hæð',

    /* hverfi */
    'nb.kicker': '07 — Hverfi',
    'nb.title': 'Hnoðraholt',
    'nb.body': 'Lóðin við Vorbraut 14 er hugsuð sem rólegt og aðlaðandi umhverfi fyrir íbúa — með leiksvæði, gróðri, göngustígum og góðum tengslum milli húss, garða og sameiginlegra svæða. Rólegt og fjölskylduvænt hverfi með útivist í næsta nágrenni.',
    'nb.note': 'Nákvæmar upplýsingar um skóla, verslun og þjónustu verða staðfestar.',

    /* contact */
    'ct.kicker': 'Hafa samband',
    'ct.title': 'Sendu fyrirspurn',
    'ct.body': 'Fylltu út formið hér að neðan og við höfum samband eins fljótt og auðið er.',
    'ct.fName': 'Nafn',
    'ct.fEmail': 'Netfang',
    'ct.fPhone': 'Símanúmer',
    'ct.fMessage': 'Skilaboð',
    'ct.fSubmit': 'Senda fyrirspurn',
    'ct.orDirect': 'Eða hafðu beint samband',
    'ct.ibudBordi': 'Fyrirspurn um íbúð',
    'ct.ibudSkilabod': 'Ég hef áhuga á íbúð {ibud} í Vorbraut 14 og vil fá nánari upplýsingar.',
    'ct.sent': 'Takk fyrir! Fyrirspurnin er komin til Miklaborgar og þú færð svar fljótlega.',
    'ct.ofhratt': 'Þú hefur sent nokkrar fyrirspurnir á stuttum tíma. Reyndu aftur eftir smá stund eða hringdu í 569 7000.',
    'ct.mailto': 'Við náðum ekki að senda hana sjálfkrafa — tölvupóstforritið þitt opnast með fyrirspurninni. Ýttu á „Senda“ þar, eða sendu á miklaborg@miklaborg.is.',
    'ct.sending': 'Sendi fyrirspurnina…',
    'ct.salesTbd': 'Söluaðili og opið hús verða auglýst þegar nær dregur. Sláðu á þráðinn fyrir nánari upplýsingar — hér koma nafn, sími og netfang söluaðila.',
    'ct.devLabel': 'Byggingaraðili',
    'ct.dev': 'Meistarasmíði ehf',
    'ct.archLabel': 'Arkitekt',
    'ct.arch': 'ARCHUS arkitektar',
    'ct.locLabel': 'Staðsetning',
    'ct.loc': 'Vorbraut 14, Hnoðraholt, Garðabær',
    'ct.landLabel': 'Landeignarnúmer',
    'ct.land': 'L232219',
    'foot.rights': 'Vorbraut 14 — Hnoðraholt, Garðabær. Myndir eru til skýringar.',
    'foot.teamLabel': 'Hönnun & framkvæmd',
  },

  en: {
    /* CMS — brand, hero, agents, footer */
    'brand.logo': 'VORBRAUT 14',
    'hero.name': 'Vorbraut',
    'hero.no': '14',
    'sellers.brand1': 'Fasteignasalan',
    'sellers.brand2': 'MIKLABORG',
    'foot.addr1': 'Vorbraut 14, Hnoðraholt',
    'foot.addr2': '210 Garðabær',
    'foot.landnr': 'L232219',
    'foot.email': 'miklaborg@miklaborg.is',
    'foot.phone': 'S: 569 7000',
    'ag.1.name': 'Steinn Andri Viðarsson',
    'ag.1.title': 'Licensed real estate & ship broker',
    'ag.1.phone': '775‑1477',
    'ag.1.email': 'steinn@miklaborg.is',
    'ag.2.name': 'Guðrún Gonnigan Daníelsdóttir',
    'ag.2.title': 'Licensed real estate agent',
    'ag.2.phone': '897‑1161',
    'ag.2.email': 'gudrun@miklaborg.is',
    'ag.3.name': 'Kjartan Ísak Guðmundsson',
    'ag.3.title': 'Licensed real estate agent',
    'ag.3.phone': '663‑4392',
    'ag.3.email': 'kjartan@miklaborg.is',
    'ag.4.name': 'Kristín Pétursdóttir',
    'ag.4.title': 'Licensed real estate & ship broker',
    'ag.4.phone': '824‑1965',
    'ag.4.email': 'kristin@miklaborg.is',
    /* ---- nav + pager (undirsíður) ---- */
    'nav.verkefnid': 'The project',
    'nav.arkitektur': 'Architecture',
    'nav.husid': 'The building',
    'nav.utsyni': 'Views and outdoor spaces',
    'nav.utirymi': 'Outdoor',
    'nav.adgengi': 'Access',
    'nav.hverfid': 'Neighbourhood',
    'nav.menu': 'Menu',
    'pager.prev': 'Previous',
    'pager.next': 'Next',
    'pager.home': 'Home',
    'pager.ibudir': 'View apartments',
    /* ---- story sections ---- */
    'fig.label': 'Fig.',
    'kj.kick': 'Below ground',
    'kj.title': 'The parking garage',
    'kj.sub': 'Ten parking spaces and a private storage room for every apartment. The lift reaches the garage from every floor.',
    'kort.kick': 'Within walking distance',
    'kort.title': 'Local amenities',
    'kort.sub': 'Everything on the map lies within 1.5 km of Vorbraut 14, measured as the crow flies.',
    'kort.credit': 'Map data © OpenStreetMap contributors',
    'kort.swipe': 'Swipe sideways to explore the map.',
    'fig.viz': 'Visualisation',
    'swipe.adur': 'Before',
    'swipe.eftir': 'After',
    'st.intro.kick': '01 · Vorbraut 14',
    'st.intro.title': 'Captivating Living in Garðabær',
    'st.intro.pull': 'Light, open views and nature in Garðabær',
    'st.intro.lvl': 'The site and the whole',
    'st.intro.cap': 'Line drawing of Vorbraut 14 — form and proportion.',
    'st.intro.cap2': 'The same viewpoint: the building under construction and completed.',
    'st.intro.cap3': 'The front elevation during construction, townscape beyond.',
    'st.intro.b1': 'At Vorbraut 14 in Hnoðraholt, Garðabær, a finely crafted four-storey residential building rises, home to 14 varied apartments together with an underground garage and generous shared spaces. The project places strong emphasis on daylight, views, exemplary accessibility and cohesive design, befitting a building that enjoys an exceptional setting high in the landscape. The house stands in a peaceful, sought-after location where proximity to untouched nature, varied services and the main transport routes comes together as one. Here lies the opportunity for a future home in which the richness of everyday life is reflected in thoughtful layouts, well-appointed outdoor areas and modern comforts. Vorbraut 14 is an ideal choice for those who set high standards for living in Garðabær, where openness and light take precedence, yet services and outdoor recreation are never far away.',
    'st.intro.c1': '14 apartments',
    'st.intro.c2': 'Four storeys',
    'st.intro.c3': 'Hnoðraholt, Garðabær',
    'st.intro.c4': 'Daylight and views',
    'st.arch.kick': '02 · Design',
    'st.arch.title': 'Architecture',
    'st.arch.pull': 'Refined form in harmony with Hnoðraholt',
    'st.arch.lvl': 'Every floor of the building',
    'st.arch.cap': 'The front elevation: white planes and timber-clad bays.',
    'st.arch.cap2': 'Sketch of the building — from idea to reality.',
    'st.arch.b1': 'The architecture of Vorbraut 14 is measured and refined, with a clear emphasis on a polished expression and harmony with its surroundings. Designed by architect Guðmundur Gunnlaugsson at Archus, the building is closely tied to the landscape of Hnoðraholt, takes its cue from the views, and sits comfortably within the development now taking shape in the area. The house carries a refined, assured and contemporary appearance, where purity of form, choice of materials and texture come together as a convincing whole. Its exterior is clad in high-quality aluminium, the surfaces broken up with varied textures to lend the facade greater depth. The recessed top floor gives the house a lighter feel while creating room for exceptionally elegant roof terraces. In this way the expansive views are used to the full and made an inseparable part of the residents\' homes. The design rests on drawing out the merits of the site, and the result is a structure defined by material quality, refinement and quiet dignity.',
    'st.arch.c1': 'Aluminium cladding',
    'st.arch.c2': 'Recessed top floor',
    'st.arch.c3': 'Archus',
    'st.arch.c4': 'Guðmundur Gunnlaugsson',
    'arch.name': 'Guðmundur Gunnlaugsson',
    'arch.role': 'Architect of the building',
    'st.house.kick': '03 · The homes',
    'st.house.title': 'The Building',
    'st.house.pull': 'Fourteen homes, countless ways to live',
    'st.house.lvl': 'Floors 1–4',
    'st.house.cap': 'The rear elevation: fourteen apartments on four floors.',
    'st.house.cap2': 'The front elevation and the approach to the main entrance.',
    'st.house.b1': 'Vorbraut 14 is a well-appointed four-storey apartment building with a lift, housing 14 carefully planned homes. The emphasis is on meeting different needs, whether that is a first purchase, moving up or scaling down. The range spans everything from efficient studios to generous family apartments where bright open living spaces come into their own.',
    'st.house.b2': 'The apartments were designed around open flow and a clear connection between indoors and out. Large windows capture the daylight beautifully, add to the sense of space and draw the surroundings straight into the living room.',
    'st.house.b3': 'The outdoor spaces are a welcome extension of the home. Ground-floor apartments open directly onto a large private terrace that brings the garden and planting closer. Upper floors have balconies and handsome roof terraces offering comfortable time outdoors and fine views across the neighbourhood.',
    'st.house.b4': 'Everyday comfort carries through to the shared facilities. Beneath the building is a closed car park with private storage for every apartment, and a lift gives easy access to all floors. There is also a spacious bicycle and pram store that makes daily life considerably easier and supports an active lifestyle.',
    'st.house.c1': 'Elevator building',
    'st.house.c2': 'Studios to family homes',
    'st.house.c3': 'Ground-floor garden plots',
    'st.house.c4': 'Large windows',
    'st.view.kick': '04 · Perspective',
    'st.view.title': 'The View',
    'st.view.pull': 'The view opens wider the higher you rise',
    'st.view.lvl': 'Upper floors and roof',
    'st.view.cap': 'Hnoðraholt from above — the neighbourhood and the golf course.',
    'st.view.cap2': 'Vífilsstaðavatn, the golf course and the mountain range.',
    'st.view.b1': 'The hilly, open setting of Vorbraut 14 is one of the project\'s unmistakable assets. The building offers a sweeping, beautiful outlook over the town and the surrounding landscape, and the vista opens up further the higher you climb. The architecture takes its cue deeply from these distinctive qualities. Large windows and balconies frame the surroundings so that the connection to nature, the light and the view is woven into the texture of everyday life. This expansive outlook gives the homes a priceless treasure and underscores the sense that the living spaces are not bounded by their walls alone.',
    'st.view.c1': 'Sweeping views',
    'st.view.c2': 'Town views',
    'st.view.c3': 'Balconies',
    'st.view.c4': 'Hilly setting',
    'st.outdoor.kick': '05 · Nature',
    'st.outdoor.title': 'Outdoor Spaces',
    'st.outdoor.pull': 'Outdoor spaces that extend the home',
    'st.outdoor.lvl': 'Private terraces and roof decks',
    'st.outdoor.cap': 'The plot, the lawns and the green roof from above.',
    'st.outdoor.cap2': 'Approach, planting and ground-floor private areas.',
    'st.outdoor.b1': 'The outdoor spaces of the property play a key role in the living quality of Vorbraut 14. Those on the ground floor can enjoy private garden areas that create closeness and a strong connection to the lush surroundings. The balconies and roof terraces of the upper floors, in turn, offer fresh air and incomparable views. A green roof covers part of the rooftop, softening the building\'s appearance and harmonising beautifully with the natural character of the heath. The grounds also draw on blue-green solutions for stormwater management that blend seamlessly into the area\'s refined appearance. In this way the outdoor spaces extend the home and enhance quality of life by bringing the surroundings closer to the residents.',
    'st.outdoor.c1': 'Private garden areas',
    'st.outdoor.c2': 'Green roof',
    'st.outdoor.c3': 'Blue-green solutions',
    'st.outdoor.c4': 'Stormwater management',
    'st.access.kick': '06 · Comfort',
    'st.access.title': 'Access and Support Spaces',
    'st.access.mark': 'Basement',
    'st.access.pull': 'Thought through for every day, garage to home',
    'st.access.lvl': 'Parking basement and support spaces',
    'st.access.cap': 'The main entrance with its accessible ramp.',
    'st.access.cap2': 'The ramp down into the enclosed parking basement.',
    'st.access.b1': 'Impeccable everyday comfort runs as a thread throughout the work. A spacious elevator serves every floor and the parking garage, ensuring universal, effortless access. The enclosed garage provides a dedicated parking space and private storage unit for each apartment. Residents also have access to a generous bicycle and stroller room that lends particular support to people on the go and to families with children. All of these spaces are designed to frame an organised, simple home life in which the daily use of the building is effortless. Waste handling is neatly arranged with sunken deep containers that enhance both the cleanliness and the aesthetics of the immediate surroundings.',
    'st.access.c1': 'Spacious elevator',
    'st.access.c2': 'Enclosed garage',
    'st.access.c3': 'Private storage',
    'st.access.c4': 'Bicycle & stroller room',
    'st.access.c5': 'Sunken deep containers',
    'st.hood.kick': '07 · Location',
    'st.hood.title': 'The Neighbourhood',
    'st.hood.mark': 'The holt',
    'st.hood.pull': 'Where nature and town meet',
    'st.hood.lvl': 'Hnodraholt in Gardabaer',
    'st.hood.cap': 'Vifilsstadavatn and the golf course at Vetrarmyri.',
    'st.hood.cap2': 'Recreation, services and main roads within walking distance.',
    'st.hood.b1': 'Hnoðraholt is a vibrant, flourishing residential neighbourhood that blends untouched nature with short distances to transport and services. The area sits close to the region\'s main arteries yet preserves its calm, family-friendly character, with ideal conditions for outdoor life. There is easy, convenient access to popular recreation spots such as Vífilsstaðavatn lake, the walking and cycling trails of Heiðmörk, and the GKG golf course. Living here is therefore especially well suited to those who like to step straight out into the open air with little effort. Alongside the natural surroundings, Garðabær offers a rich array of leisure and services. Quality shops, fine restaurants, sports centres and strong infrastructure together create a setting that is both lively and secure for residents of every age.',
    'st.hood.c1': 'Vífilsstaðavatn lake',
    'st.hood.c2': 'Heiðmörk trails',
    'st.hood.c3': 'GKG golf course',
    'st.hood.c4': 'Family-friendly',
    'nav.house': 'The building',
    'nav.ibudir': 'Apartments',
    'nav.stadsetning': 'Location',
    'nav.honnun': 'Design',
    'nav.gaedi': 'Quality',
    'nav.hverfi': 'Neighbourhood',
    'nav.contact': 'Contact',
    'cta.ibudir': 'View apartments',
    'cta.contact': 'Get in touch',
    'cta.enquiry': 'Send an enquiry',
    'cta.plan': 'View floor plan',
    'scroll': 'Scroll',

    'hero.kicker': 'Hnoðraholt · Garðabær',
    'hero.eyebrow': 'Vorbraut 14 · Hnoðraholt',
    'hero.headline': 'Quality apartments in a remarkable setting',
    'hero.h1': 'Refined',
    'hero.h2': 'homes',
    'hero.h3': 'in a singular place',
    'hero.lead': 'Choose an apartment to see its location, size, layout and sales status.',
    'hero.title': 'Vorbraut 14',
    'hero.tag': 'Refined apartments in Hnoðraholt, Garðabær.',
    'hero.sub': 'New apartments in Garðabær are now for sale.',
    'stat.ibudir': 'apartments',
    'stat.haedir': 'floors',
    'stat.bilastaedi': 'parking spaces',
    'stat.fra': 'm² from',

    'loc.kicker': '02 — Location',
    'loc.title': 'Ample parking and a great location',
    'loc.body': 'Vorbraut 14 sits in Hnoðraholt in Garðabær — a calm, family-friendly setting with recreation nearby and easy access to the main roads.',
    'loc.p1.t': '10 parking spaces',
    'loc.p1.b': 'All 10 spaces are in a closed, locked garage.',
    'loc.p2.t': 'EV charging ready',
    'loc.p2.b': 'Charging equipment is planned to be easy to install, both in the garage and at the lot spaces.',
    'loc.p3.t': 'Storage & bicycles',
    'loc.p3.b': 'The basement holds a private storage unit for each home plus a spacious bicycle and pram room.',
    'loc.p4.t': 'Accessible for all',
    'loc.p4.b': 'A central lift and universal design connect the apartments, common areas and garage.',

    'apt.kicker': '03 — Apartments',
    'apt.title': 'Bright apartments, designed to live in',
    'apt.body': 'Homes range from two-room apartments to generous four-room apartments on the top floor. The focus is on flow, daylight and usability. Underfloor heating throughout and careful acoustic detailing.',
    'type.two.name': '2-room',
    'type.two.size': '69–70 m²',
    'type.two.desc': 'Efficient, well-planned homes for individuals and couples.',
    'type.fam.name': '3–4 room',
    'type.fam.size': '102–118 m²',
    'type.fam.desc': 'Spacious family homes, some with private terraces on the ground floor.',
    'type.pent.name': 'Top floor',
    'type.pent.size': '156–158 m²',
    'type.pent.desc': 'Larger homes with raised ceilings and generous roof terraces.',

    'sel.kicker': 'Apartments at Vorbraut 14',
    'sel.title': 'Choose an apartment in the building',
    'sel.brand': 'Vorbraut 14',
    'av.tabPlan': 'Floor plan',
    'av.tabGarage': 'See parking garage',
    'av.kjStaedi': 'Parking space',
    'av.kjGeymsla': 'Private storage',
    'av.kjEkkert': 'No parking space is included with this apartment.',
    'av.cta': 'Enquire about this apartment',
    'av.call': 'Or call',
    'av.zoom': 'Click the floor plan to view in higher resolution',
    'av.spec': 'Specification',
    'kj.flatarmal': 'Garage',
    'kj.geymslur': 'Storage units',
    'kj.adgengi': 'Access',
    'kj.adgengiGildi': 'Lift and ramp',
    'kj.cta': 'See access',
    'av.garage': 'Parking garage plan',
    'facade.aftan': 'Rear',
    'facade.framan': 'Front',
    'facade.hlid': 'Side',
    'facade.kjallari': 'Parking garage',
    'sel.pickFloor': 'Select floor',
    'sel.pickApt': 'Select apartment',
    'sel.body': 'Move your cursor over the building. Each apartment lights up — click to see size, floor, rooms and floor plan.',
    'sel.bodyTouch': 'Click or tap an apartment to see floor plans, sizes and more details.',
    'sel.empty': 'Select an apartment on the building or on the floor plan.',
    'sel.open': 'View apartment',
    'facade.front': 'Front',
    'facade.back': 'Rear',
    'sel.hint': 'Select an apartment on the image',
    'sel.legend.available': 'Available',
    'sel.legend.reserved': 'Reserved',
    'sel.legend.sold': 'Sold',

    'list.kicker': '04 — Overview',
    'list.title': 'All apartments',
    'filter.floor': 'Floor',
    'filter.rooms': 'Rooms',
    'filter.type': 'Type',
    'filter.all': 'All',
    'filter.reset': 'Reset',
    'apts.title': 'Price list',
    'apts.sub': 'Prices are subject to change',
    'apts.view': 'View',
    'feat.title': 'Apartment features',
    'feat.parking': 'Private parking',
    'feat.pottur': 'Option for a hot tub',
    'feat.forsale': 'For-sale apartments only',
    'sellers.title': 'Sales agents',
    'sellers.lead': 'Miklaborg real estate handles the sale of apartments at Vorbraut 14. Contact an agent for more information or to book a private viewing.',
    'list.count': 'apartments',
    'list.empty': 'No apartment matches your selection. Reset the filters.',
    'col.id': 'Apt.',
    'col.floor': 'Floor',
    'col.size': 'Size',
    'col.rooms': 'Rooms',
    'col.outdoor': 'Outdoor',
    'col.status': 'Status',

    'lbl.floor': 'floor',
    'lbl.rooms': 'rooms',
    'unit.rooms2': '2 rooms',
    'unit.rooms3': '3 rooms',
    'unit.rooms4': '4 rooms',
    'out.verond': 'Terrace / private area',
    'out.svalir': 'Balcony',
    'out.thaksvalir': 'Roof terrace',
    'st.available': 'Available',
    'st.reserved': 'Reserved',
    'st.sold': 'Sold',
    'spec.ceiling': 'Ceiling height',
    'spec.area': 'Floor area',
    'modal.note': 'Sizes and room counts per the main drawings. Confirmed in the purchase agreement.',
    'modal.planSoon': 'Representative floor plan for this apartment type.',
    'modal.planHint': 'Click the floor plan to view it in higher resolution.',
    'modal.planDisc': 'Areas shown are the net published areas per the main drawings. Refer to the registration table for gross and published square metres. Confirmed in the purchase agreement.',
    'modal.floorLbl': 'Floor',
    'spec.parking': 'Parking space',
    'spec.storage': 'Private storage',
    'spec.balcony': 'Balcony / terrace',
    'spec.laundry': 'Private laundry',
    'spec.theme': 'Design theme',
    'spec.price': 'Price',
    'spec.no': 'No',
    'spec.yes': 'Yes',
    'spec.basement': 'In the basement',

    'des.kicker': '05 — Design',
    'des.title': 'Clean and timeless',
    'des.body': 'The building is designed by architect Guðmundur Gunnlaugsson at ARCHUS architects. White aluminium cladding, natural timber and glass railings lighten its presence. Charcoal-grey windows and warm timber tones create a calm, northern character that fits Hnoðraholt.',
    'des.architect': 'ARCHUS architects — Guðmundur Gunnlaugsson',

    'q.kicker': '06 — Quality',
    'q.title': 'Quality per the main drawings',
    'q.body': 'Durable materials, good accessibility and a clear interior layout run through the whole building.',
    'q.1': 'Underfloor heating in every home',
    'q.2': 'Quality acoustics and insulation',
    'q.3': 'Natural ventilation with mechanical extraction',
    'q.4': 'Lift and universal design',
    'q.5': 'Waste sorting in deep containers',
    'q.6': 'EV charging option',
    'q.7': 'Large windows and good daylight',
    'q.8': 'Roof terraces with raised ceilings on the top floor',

    'nb.kicker': '07 — Neighbourhood',
    'nb.title': 'Hnoðraholt',
    'nb.body': 'The grounds at Vorbraut 14 are conceived as a calm, welcoming setting — with a play area, planting, footpaths and good connections between the building, gardens and shared spaces. A quiet, family-friendly area with recreation close by.',
    'nb.note': 'Precise details on schools, shops and services will be confirmed.',

    'ct.kicker': 'Contact',
    'ct.title': 'Send an inquiry',
    'ct.body': 'Fill out the form below and we will get back to you as soon as possible.',
    'ct.fName': 'Name',
    'ct.fEmail': 'Email',
    'ct.fPhone': 'Phone',
    'ct.fMessage': 'Message',
    'ct.fSubmit': 'Send inquiry',
    'ct.ibudBordi': 'Inquiry about apartment',
    'ct.ibudSkilabod': 'I am interested in apartment {ibud} at Vorbraut 14 and would like more information.',
    'ct.orDirect': 'Or contact us directly',
    'ct.sent': 'Thank you! Your enquiry has reached Miklaborg and you will hear back shortly.',
    'ct.ofhratt': 'You have sent several enquiries in a short time. Please try again shortly or call +354 569 7000.',
    'ct.mailto': 'We could not send it automatically — your email app will open with the enquiry. Press Send there, or write to miklaborg@miklaborg.is.',
    'ct.sending': 'Sending your enquiry…',
    'ct.salesTbd': 'The sales agent and open house will be announced closer to launch. Get in touch for details — the agent name, phone and email will appear here.',
    'ct.devLabel': 'Developer',
    'ct.dev': 'Meistarasmíði ehf',
    'ct.archLabel': 'Architect',
    'ct.arch': 'ARCHUS architects',
    'ct.locLabel': 'Location',
    'ct.loc': 'Vorbraut 14, Hnoðraholt, Garðabær',
    'ct.landLabel': 'Land registry no.',
    'ct.land': 'L232219',
    'foot.rights': 'Vorbraut 14 — Hnoðraholt, Garðabær. Images are illustrative.',
    'foot.teamLabel': 'Design & construction',
  }
};
window.VB = window.VB || {};
window.VB.STR = STR;
// Vísvitandi tómur texti (notandi eyddi honum) — geymt sem þetta tákn í gagnagrunni
// svo það ruglist ekki saman við „óvart tómt“ (sem fellur aftur í sjálfgildi).
window.VB.BLANK = '__VB_BLANK__';
